# Generated by Django 5.1.5 on 2025-02-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classificationID', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurementID', models.AutoField(primary_key=True, serialize=False)),
                ('measureName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purposeID', models.AutoField(primary_key=True, serialize=False)),
                ('purposeName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.AutoField(primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('itmName', models.CharField(max_length=500)),
                ('itemQuantity', models.IntegerField(default=0)),
                ('unitCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('classificationID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.classification')),
            ],
        ),
        migrations.CreateModel(
            name='RunningBalance',
            fields=[
                ('runningBalID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('beginningBalance', models.IntegerField(null=True)),
                ('purchasedFromSupp', models.IntegerField()),
                ('returnToSupplier', models.CharField(max_length=500)),
                ('transferFromWH', models.CharField(max_length=500)),
                ('transferToWH', models.CharField(max_length=500)),
                ('issuedQty', models.IntegerField(blank=True, null=True)),
                ('consumption', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('totalCost', models.FloatField(blank=True, null=True)),
                ('classID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.classification')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('measureID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('week', models.CharField(max_length=25)),
                ('mris', models.IntegerField()),
                ('supplier', models.CharField(max_length=500)),
                ('requestedBy', models.CharField(max_length=500)),
                ('Area', models.CharField(max_length=500)),
                ('purchasedQty', models.IntegerField(blank=True, null=True)),
                ('returnToSupplier', models.CharField(max_length=500)),
                ('transferFromWH', models.CharField(max_length=500)),
                ('transferToWH', models.CharField(max_length=500)),
                ('issuedQty', models.IntegerField(blank=True, null=True)),
                ('returnedQty', models.IntegerField(blank=True, null=True)),
                ('consumption', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('totalCost', models.FloatField(blank=True, null=True)),
                ('classificationID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.classification')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('purposeID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.purpose')),
                ('sectionID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.section')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('week', models.CharField(max_length=500)),
                ('classID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.classification')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('sectionID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.section')),
                ('transactionID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.transaction')),
            ],
        ),
    ]
