# Generated by Django 5.1.6 on 2025-02-19 01:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaID', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classificationID', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurementID', models.AutoField(primary_key=True, serialize=False)),
                ('measureName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purposeID', models.AutoField(primary_key=True, serialize=False)),
                ('purposeName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.AutoField(primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=500)),
                ('itemQuantity', models.IntegerField(default=0)),
                ('unitCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classificationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.classification')),
                ('measurementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transactionDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='2025-02-19')),
                ('week', models.CharField(max_length=25)),
                ('mris', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=500)),
                ('requestedBy', models.CharField(blank=True, max_length=500)),
                ('purposeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.purpose')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.section')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProduct',
            fields=[
                ('transactionProductID', models.AutoField(primary_key=True, serialize=False)),
                ('purchasedFromSupp', models.IntegerField(blank=True, default=0)),
                ('returnToSupplier', models.IntegerField(blank=True, default=0)),
                ('transferFromWH', models.IntegerField(blank=True, default=0)),
                ('transferToWH', models.IntegerField(blank=True, default=0)),
                ('issuedQty', models.IntegerField(blank=True, default=0)),
                ('returnedQty', models.IntegerField(blank=True, default=0)),
                ('consumption', models.IntegerField(default=0)),
                ('areaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.area')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('transactionDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.transactiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='RunningBalance',
            fields=[
                ('runningBalID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('beginningBalance', models.IntegerField(null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('TransactionProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.transactionproduct')),
            ],
        ),
    ]
