# Generated by Django 5.1.5 on 2025-02-07 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measurementID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.measurement'),
        ),
    ]
