# Generated by Django 5.1.6 on 2025-02-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='purposeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.purpose'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='sectionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.section'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='areaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.area'),
        ),
    ]
