# Generated by Django 5.1.6 on 2025-03-10 01:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 1, 52, 27, 796900, tzinfo=datetime.timezone.utc)),
        ),
    ]
