# Generated by Django 5.1.5 on 2025-02-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchasedQty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
