# Generated by Django 5.1.6 on 2025-03-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumption',
            name='TransactionProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.transactionproduct'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-03-06'),
        ),
    ]
