# Generated by Django 5.1.6 on 2025-02-17 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transactionDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week', models.CharField(max_length=25)),
                ('mris', models.IntegerField()),
                ('supplier', models.CharField(max_length=500)),
                ('requestedBy', models.CharField(max_length=500)),
                ('purposeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.purpose')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.section')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProduct',
            fields=[
                ('transactionProductID', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=500)),
                ('purchasedFromSupp', models.IntegerField(blank=True, default=0)),
                ('returnToSupplier', models.IntegerField(blank=True, default=0)),
                ('transferFromWH', models.IntegerField(blank=True, default=0)),
                ('transferToWH', models.IntegerField(blank=True, default=0)),
                ('issuedQty', models.IntegerField(blank=True, default=0)),
                ('returnedQty', models.IntegerField(blank=True, default=0)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('transactionDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.transactiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transactionDetailsID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.transactiondetails')),
                ('TransactionProductID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.transactionproduct')),
            ],
        ),
    ]
