# Generated by Django 5.1.6 on 2025-03-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_transactiondetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-03-10'),
        ),
    ]
