# Generated by Django 5.1.6 on 2025-02-19 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_alter_transactiondetails_purposeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginningBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.CharField(max_length=20)),
                ('itemName', models.CharField(max_length=500)),
                ('itemQuantity', models.IntegerField(default=0)),
                ('unitCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('measurementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.measurement')),
            ],
        ),
    ]
