# Generated by Django 5.1.6 on 2025-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_transactiondetails_transactionproduct_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='requestedBy',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='supplier',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
