# Generated by Django 5.1.6 on 2025-03-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_monthlyconsumption_transactionproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyconsumption',
            old_name='TransactionProduct',
            new_name='TransactionProductID',
        ),
    ]
