# Generated by Django 5.1.6 on 2025-03-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_rename_transactionproduct_monthlyconsumption_transactionproductid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyconsumption',
            old_name='TransactionProductID',
            new_name='transactionProductID',
        ),
    ]
