# Generated by Django 5.1.5 on 2025-02-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_measurement_measurementid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurementID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
