# Generated by Django 5.1.6 on 2025-02-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_beginningbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningbalance',
            name='TransactionProductID',
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='issuedQty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='itemName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='itemQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='measurementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.measurement'),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='purchasedFromSupp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='returnToSupplier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='returnedQty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='transferFromWH',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='transferToWH',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runningbalance',
            name='unitCost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='runningbalance',
            name='beginningBalance',
            field=models.IntegerField(default=0),
        ),
    ]
