# Generated by Django 5.1.5 on 2025-02-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_transactiondetails_requestedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-02-18'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='area',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
