# Generated by Django 5.1.5 on 2025-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_transactiondetails_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproduct',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
    ]
