# Generated by Django 5.1.5 on 2025-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_measurement_measurementid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
