# Generated by Django 5.1.6 on 2025-03-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_rename_transactionproductid_monthlyconsumption_transactionproductid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-03-07'),
        ),
    ]
