# Generated by Django 5.1.6 on 2025-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_remove_runningbalance_transactionproductid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningbalance',
            name='runningBalID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
