# Generated by Django 5.1.5 on 2025-02-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_alter_item_totalcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='totalCost',
        ),
    ]
