# Generated by Django 5.1.6 on 2025-02-19 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_transactionproduct_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-02-19'),
        ),
        migrations.CreateModel(
            name='RunningBalance',
            fields=[
                ('runningBalID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('beginningBalance', models.IntegerField(null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('TransactionProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.transactionproduct')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
            ],
        ),
    ]
