# Generated by Django 5.1.6 on 2025-02-19 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_alter_runningbalance_runningbalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumptionTotal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalNSC', models.IntegerField(default=0)),
                ('totalProd', models.IntegerField(default=0)),
                ('totalMeterMaintenance', models.IntegerField(default=0)),
                ('totalSpecialProj', models.IntegerField(default=0)),
                ('totalConstruction', models.IntegerField(default=0)),
                ('totalCommercial', models.IntegerField(default=0)),
                ('totalSales', models.IntegerField(default=0)),
                ('totalGenService', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='transactionproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('monthlyConsumptionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('week', models.CharField(max_length=500)),
                ('itemName', models.CharField(max_length=100)),
                ('consumption', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.section')),
            ],
        ),
    ]
