# Generated by Django 5.1.6 on 2025-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_monthlyconsumptiontotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumption',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
