# Generated by Django 5.1.5 on 2025-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_remove_item_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='totalCost',
            field=models.FloatField(default=0.0),
        ),
    ]
