# Generated by Django 5.1.6 on 2025-02-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_monthlyconsumption_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-02-20'),
        ),
    ]
