# Generated by Django 5.1.6 on 2025-02-20 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_alter_monthlyconsumption_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='itemName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='sectionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.section'),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='week',
            field=models.IntegerField(),
        ),
    ]
