# Generated by Django 5.1.6 on 2025-02-20 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_alter_monthlyconsumption_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
