# Generated by Django 5.1.6 on 2025-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_alter_monthlyconsumption_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='week',
            field=models.CharField(max_length=255),
        ),
    ]
