# Generated by Django 5.1.6 on 2025-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_alter_monthlyconsumption_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='week',
            field=models.IntegerField(),
        ),
    ]
