# Generated by Django 5.1.6 on 2025-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_alter_monthlyconsumption_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptiontotal',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyconsumption',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
