# Generated by Django 5.1.6 on 2025-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0013_monthlyconsumptiontotal_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptiontotal',
            name='totalConsuptions',
            field=models.IntegerField(default=0),
        ),
    ]
