# Generated by Django 5.1.6 on 2025-02-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_monthlyconsumptiontotal_totalconsuptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyconsumptiontotal',
            old_name='totalConsuptions',
            new_name='totalConsumptions',
        ),
    ]
