# Generated by Django 5.1.6 on 2025-02-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_rename_totalconsuptions_monthlyconsumptiontotal_totalconsumptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyconsumptiontotal',
            old_name='totalConsumptions',
            new_name='totalConsumption',
        ),
    ]
