# Generated by Django 5.1.5 on 2025-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0016_rename_totalconsumptions_monthlyconsumptiontotal_totalconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningbalance',
            name='measureName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
