# Generated by Django 5.1.5 on 2025-02-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0017_runningbalance_measurename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningbalance',
            name='measureName',
        ),
    ]
