# Generated by Django 5.1.6 on 2025-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0018_remove_runningbalance_measurename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateField(default='2025-02-23'),
        ),
    ]
