#login API
POST http://127.0.0.1:8000/ims/login/
Content-Type: application/json

{"username": "admin", "password": "admin"}

###
# signup API
POST http://127.0.0.1:8000/ims/create_user/
Content-Type: application/json

{"username": "admin", "password": "admin","email": "admin@email.com"}

###
#test_token API
GET http://127.0.0.1:8000/ims/test_token/
Content-Type: application/json
Authorization: Token d80c574a5c35767e4e027e4634262861ef723d44

{}

###

POST http://127.0.0.1:8000/ims/api-token-auth/
Content-Type: application/json

{"username": "admin", "password": "admin"}